name: flutter_experiments
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.0-134.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Sending Notifications
  dio: ^4.0.4
  flutter_dotenv: ^5.0.2
  firebase_core: ^1.12.0
  firebase_database: ^9.0.6
  # Notifications
  firebase_messaging: ^11.2.6
  flutter_local_notifications: ^9.2.0
  # Face Detection
  google_ml_vision: ^0.0.7
  path: ^1.8.1
  path_provider: ^2.0.8
  image_picker: ^0.8.4+7
  image: ^3.1.1

  # WebSocket Chat
  web_socket_channel: ^2.1.0

  # OTP 2 Factor.in
  fluttertoast: ^8.0.8
  http: ^0.13.4
  pinput: ^1.2.2
  # Firebase Storage
  file_picker: ^4.3.3
  firebase_storage: ^10.2.7

  # Paytm
  paytm_allinonesdk: ^1.1.4

  # Google Auth
  google_sign_in: ^5.2.3

  # Shimmer Effect
  shimmer: ^2.0.0
  flutter_inset_box_shadow: ^1.0.7

flutter:
  uses-material-design: true

  assets:
    - lib/.env
    # Feature Discovery
    - assets/images/pic.png
