name: flutter_experiments
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: "^3.0.0"

dependencies:
  adaptive_action_sheet: ^2.0.2
  adaptive_breakpoints: ^0.1.6
  adaptive_components: ^0.0.9
  adaptive_navigation: ^0.0.9
  animations: ^2.0.7
  avatar_glow: ^2.0.2
  circle_nav_bar: ^2.0.1+1
  cloud_firestore: ^4.9.0
  collection: ^1.17.1
  connectivity_plus: ^4.0.2
  csv: ^5.0.2
  cupertino_icons: ^1.0.5
  date_format: ^2.0.7
  delayed_display: ^2.0.0
  desktop_window: ^0.4.0
  device_info_plus: ^9.0.3
  dio: ^5.3.2
  dynamic_color: ^1.6.6
  english_words: ^4.0.0
  extra_alignments: ^1.0.0+1
  fading_edge_scrollview: ^3.0.0
  file_picker: ^5.3.3
  firebase_auth: ^4.8.0
  firebase_core: ^2.12.0
  firebase_database: ^10.2.5
  firebase_messaging: ^14.6.7
  firebase_storage: ^11.2.6
  fl_chart: ^0.63.0
  flextras: ^1.0.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0
  flutter_bloc: ^8.1.2
  flutter_blue_plus: ^1.14.11
  flutter_dotenv: ^5.0.2
  flutter_inset_box_shadow: ^1.0.8
  flutter_local_notifications: ^15.1.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.2
  flutter_native_timezone: ^2.0.0
  flutter_riverpod: ^2.3.7
  flutter_screenutil: ^5.9.0
  flutter_spinkit: ^5.2.0
  flutter_staggered_grid_view: ^0.7.0
  # flutter_stripe: ^9.3.0
  # flutter_stripe_web: ^4.3.0
  flutter_svg: ^2.0.7
  fluttericon: ^2.0.0
  fluttertoast: ^8.2.1
  focusable_control_builder: ^1.0.2+1
  font_awesome_flutter: ^10.5.0
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  github: ^9.17.0
  go_router: ^10.1.0
  google_fonts: ^5.1.0
  google_maps_flutter: ^2.4.0
  google_ml_vision: ^0.0.8
  google_sign_in: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.3.7
  http: ^1.1.0
  image: ^4.0.17
  image_cropper: ^5.0.0
  image_picker: ^1.0.2
  in_app_purchase: ^3.1.8
  intl: ^0.18.0
  intl_phone_number_input: ^0.7.3+1
  local_auth: ^2.1.6
  local_hero: ^0.2.0
  location: ^5.0.3
  lottie: ^2.6.0
  material_color_utilities: 0.5.0
  math_expressions: ^2.4.0
  modal_bottom_sheet: ^2.1.2

  nfc_manager: ^3.3.0
  oauth2: ^2.0.1
  package_info_plus: ^4.1.0
  page_flip_builder: ^0.1.3
  palette_generator: ^0.3.3+2
  particle_field: ^1.0.0
  path: ^1.8.2
  path_provider: ^2.1.0
  paytm_allinonesdk: ^1.2.1
  permission_handler: ^10.4.3
  pie_chart: ^5.3.2
  pinput: ^3.0.0
  platform: ^3.1.1
  platform_device_id: ^1.0.1
  provider: ^6.0.5
  rnd: ^0.2.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0
  show_up_animation: ^2.0.0
  simple_animations: ^5.0.2
  sqflite: ^2.3.0
  square_percent_indicater: ^0.1.0
  stripe_checkout: ^1.0.0
  timezone: ^0.9.2
  toast: ^0.3.0
  transparent_image: ^2.0.1
  tuple: ^2.0.2
  universal_platform: ^1.0.0+1
  url_launcher: ^6.1.12
  uuid: ^3.0.7
  vector_math: ^2.1.4
  web_socket_channel: ^2.4.0
  webdriver: ^3.0.2
  websafe_svg: ^3.0.1+1
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  flutter_lints: ^2.0.2
  msix: ^3.16.1
flutter:
  uses-material-design: true

  assets:
    - lib/.env
    - assets/images/playlists/
    - assets/images/albums/
    - assets/images/artists/
    - assets/images/news/
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/
  shaders:
    - assets/shaders/orb_shader.frag
    - assets/shaders/ui_glitch.frag

# Flutter native scrips
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware
# For details regarding adding assets from package dependencies, see
# https://flutter.dev/assets-and-images/#from-packages
# To add custom fonts to your application, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts from package dependencies,
# see https://flutter.dev/custom-fonts/#from-packages
flutter_native_splash:
  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove
  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.
  color: "#e1f5fe"
  #background_image: "assets/background.png"
  # Optional parameters are listed below.  To enable a parameter, uncomment the line by removing
  # the leading # character.
  # The image parameter allows you to specify an image used in the splash screen.  It must be a
  # png file and should be sized for 4x pixel density.
  image: assets/logo_lockup_flutter_vertical.png

  # The branding property allows you to specify an image used as branding in the splash screen.
  # It must be a png file. Currently, it is only supported for Android < v12 and iOS.
  #branding: assets/dart.png
  # To position the branding image at the bottom of the screen you can use bottom, bottomRight,
  # and bottomLeft. The default values is bottom if not specified or specified something else.
  #branding_mode: bottom
  # The color_dark, background_image_dark, image_dark, branding_dark are parameters that set the background
  # and image when the device is in dark mode. If they are not specified, the app will use the
  # parameters from above. If the image_dark parameter is specified, color_dark or
  # background_image_dark must be specified.  color_dark and background_image_dark cannot both be
  # set.
  color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  image_dark: assets/logo_lockup_flutter_vertical_wht.png
  #branding_dark: assets/dart_dark.png
  # Android 12 handles the splash screen differently than previous versions.  Please visit
  # https://developer.android.com/guide/topics/ui/splash-screen
  # Following are Android 12 specific parameter.
  android_12: null
  # The image parameter sets the splash screen icon image.  If this parameter is not specified,
  # the app's launcher icon will be used instead.
  # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
  # 640 pixels in diameter.
  # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
  # 768 pixels in diameter.
  #image: assets/android12splash.png
  # Splash screen background color.
  #color: "#42a5f5"
  # App icon background color.
  #icon_background_color: "#eeeeee"
  # The image_dark parameter and icon_background_color_dark set the image and icon background
  # color when the device is in dark mode. If they are not specified, the app will use the
  # parameters from above.
  #image_dark: assets/android12splash-invert.png
  #color_dark: "#042a49"
  #icon_background_color_dark: "#111111"
  # The android, ios and web parameters can be used to disable generating a splash screen on a given
  # platform.
  #android: false
  #ios: false
  #web: false
  # The position of the splash image can be set with android_gravity, ios_content_mode, and
  # web_image_mode parameters.  All default to center.
  #
  # android_gravity can be one of the following Android Gravity (see
  # https://developer.android.com/reference/android/view/Gravity): bottom, center,
  # center_horizontal, center_vertical, clip_horizontal, clip_vertical, end, fill, fill_horizontal,
  # fill_vertical, left, right, start, or top.
  #android_gravity: center
  #
  # ios_content_mode can be one of the following iOS UIView.ContentMode (see
  # https://developer.apple.com/documentation/uikit/uiview/contentmode): scaleToFill,
  # scaleAspectFit, scaleAspectFill, center, top, bottom, left, right, topLeft, topRight,
  # bottomLeft, or bottomRight.
  #ios_content_mode: center
  #
  # web_image_mode can be one of the following modes: center, contain, stretch, and cover.
  #web_image_mode: center
  # The screen orientation can be set in Android with the android_screen_orientation parameter.
  # Valid parameters can be found here:
  # https://developer.android.com/guide/topics/manifest/activity-element#screen
  #android_screen_orientation: sensorLandscape
  # To hide the notification bar, use the fullscreen parameter.  Has no affect in web since web
  # has no notification bar.  Defaults to false.
  # NOTE: Unlike Android, iOS will not automatically show the notification bar when the app loads.
  #       To show the notification bar, add the following code to your Flutter app:
  #       WidgetsFlutterBinding.ensureInitialized();
  #       SystemChrome.setEnabledSystemUIOverlays([SystemUiOverlay.bottom, SystemUiOverlay.top]);
  fullscreen: true
  # If you have changed the name(s) of your info.plist file(s), you can specify the filename(s)
  # with the info_plist_files parameter.  Remove only the # characters in the three lines below,
  # do not remove any spaces:
  #info_plist_files:
  #  - 'ios/Runner/Info-Debug.plist'
  #  - 'ios/Runner/Info-Release.plist'
