// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOAOYzGla-n-Cht_bMQiqCoNVYjyKmOps',
    appId: '1:18768737331:web:87619ea7635087c8861f46',
    messagingSenderId: '18768737331',
    projectId: 'experiments-d77a5',
    authDomain: 'experiments-d77a5.firebaseapp.com',
    storageBucket: 'experiments-d77a5.appspot.com',
    measurementId: 'G-CCQ2DDQGQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDizRvjssHyeMlEC0hpLeFcXiSBujvNg4g',
    appId: '1:18768737331:android:a5f6af418b667149861f46',
    messagingSenderId: '18768737331',
    projectId: 'experiments-d77a5',
    storageBucket: 'experiments-d77a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyBrXrFctyF0loY_T6SZhRtFs7pVIUTFE',
    appId: '1:18768737331:ios:67076dc1008ea3c8861f46',
    messagingSenderId: '18768737331',
    projectId: 'experiments-d77a5',
    storageBucket: 'experiments-d77a5.appspot.com',
    iosClientId: '18768737331-ert0jgdpr3ref5pvuuv0mcq9s7tudh3r.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterExperiments',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyBrXrFctyF0loY_T6SZhRtFs7pVIUTFE',
    appId: '1:18768737331:ios:67076dc1008ea3c8861f46',
    messagingSenderId: '18768737331',
    projectId: 'experiments-d77a5',
    storageBucket: 'experiments-d77a5.appspot.com',
    iosClientId: '18768737331-ert0jgdpr3ref5pvuuv0mcq9s7tudh3r.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterExperiments',
  );
}
